// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAIERnWjWsVqKduU4sQilAJwkdvz7dggM',
    appId: '1:941259303282:web:2fc863da318535182815eb',
    messagingSenderId: '941259303282',
    projectId: 'flutter-rent',
    authDomain: 'flutter-rent.firebaseapp.com',
    storageBucket: 'flutter-rent.appspot.com',
    measurementId: 'G-J0DXB7ZGH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVadfLHV8LoIDG4uk-wQIan1D-7Mde2w',
    appId: '1:941259303282:android:3d8b406399300b482815eb',
    messagingSenderId: '941259303282',
    projectId: 'flutter-rent',
    storageBucket: 'flutter-rent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLBrWawx5AxTuu-IjNfaRL6oRzbXP-qDo',
    appId: '1:941259303282:ios:a847e7e933f3e80c2815eb',
    messagingSenderId: '941259303282',
    projectId: 'flutter-rent',
    storageBucket: 'flutter-rent.appspot.com',
    iosClientId: '941259303282-903spuua1a58ofskt149k2avl15v6dlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationCal',
  );
}
